version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=rocket
  web:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "5000:5000"
